export enum Tipo {
    INICIO_TRABALHO = "INICIO_TRABALHO",
    TERMINO_TRABALHO = "TERMINO_TRABALHO",
    INICIO_ALMOCO = "INICIO_ALMOCO",
    TERMINO_ALMOCO = "TERMINO_ALMOCO",
    INICIO_PAUSA = "INICIO_PAUSA",
    TERMINO_PAUSA = "TERMINO_PAUSA"
}